site_name: OpenTerrace Documentation
site_author: Jakob Hærvig
site_description: >-
  OpenTerrace Documentation

repo_url: https://github.com/OpenTerrace/openterrace-python
edit_uri: blob/main/docs/
repo_name: openterrace-python/

theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  features:
    - search.highlight
    - search.share
    - search.suggest
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
    - navigation.tracking
    - toc.integrate

  palette:
    scheme: default
    primary: green
  custom_dir: docs/overrides
  logo: _figures/logo-text-icon.svg
  favicon: _figures/stone.png

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - markdown_katex:
      no_inline_svg: True
      insert_fonts_css: True

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra:
  generator: false

plugins:
- search
- autorefs
- mkdocstrings:
    default_handler: python
    handlers:
      python:
        paths: [openterrace]  # search packages in the src folder
        setup_commands:
          - import sys
          - sys.path.append('openterrace')

nav:
  - index.md
  - Installation guide: installation.md
  - User guide:
      - user-guide/get-started.md
      - Theory:
        - user-guide/theory/governing.md
      - Fluids and materials:
        - Fluids:
          - user-guide/fluid_substances/air.md
          - user-guide/ffluid_substances/water.md
        - Bed materials:
          - user-guide/bed_substances/swedish_diabase.md
          - user-guide/bed_substances/magnetite.md
          - user-guide/bed_substances/ATS58.md
      - Domain types:
          - user-guide/domains/1d_cylinder.md
          - user-guide/domains/1d_sphere.md
      - Numerical schemes:
        - Diffusion:
          - user-guide/diffusion_schemes/central_difference_1d.md
        - Convection:
          - user-guide/convection_schemes/upwind_1d.md
      - Validation and verification:
        - user-guide/verification-and-validation/verification.md
        - user-guide/verification-and-validation/validation.md
  - contributing.md
  - contact.md