site_name: Open Terrace Documentation
site_author: Jakob Hærvig
site_description: >-
  Open Terrace Documentation

repo_url: https://github.com/OpenTerrace/openterrace-python
edit_uri: blob/main/docs/
repo_name: openterrace-python/

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.tracking
    - navigation.sections
  icon:
    repo: fontawesome/brands/github
  features:
    - search.highlight
    - search.share
    - search.suggest
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
  palette:
    scheme: default
    primary: green
  custom_dir: docs/overrides

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - markdown_katex:
      no_inline_svg: True
      insert_fonts_css: True
      #macro-file: macros.tex


extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra:
  generator: false

plugins:
- mkdocstrings:
    default_handler: python
    # handlers:
    #   python:
    #     options:
    #       show_source: false


# plugins:
# - mkdocstrings:
#         handlers:
#             python:
#                 setup_commands:
#                   - import sys
#                   - sys.path.append("openterrace")
nav:
  - index.md
  - User guide:
      - user-guide/get-started.md
      - Theory:
        - user-guide/theory/governing.md
      - Fluids and materials:
        - Fluids:
          - user-guide/fluids/air.md
          - user-guide/fluids/water.md
        - Bed materials:
          - user-guide/bedmaterials/swedish_diabase.md
          - user-guide/bedmaterials/magnetite.md
          - user-guide/bedmaterials/ATS58.md
      - Validation and verification:
        - user-guide/verification-and-validation/verification.md
        - user-guide/verification-and-validation/validation.md
  - Installation guide:
      - installation/windows.md
      - installation/macos.md
      - installation/linux.md
  - Project proposals:
    - project-proposals/index.md
    - AAU:
      - project-proposals/AAU/6-semester.md
      - project-proposals/AAU/8-semester.md
      - project-proposals/AAU/10-semester.md
    - project-proposals/completed-projects.md