site_name: Open Terrace Documentation

handlers:
  python:
    setup_commands:
      - import sys
      - sys.path.append("openterrace")

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.tracking
    - navigation.sections
  icon:
    repo: fontawesome/brands/github
  palette:
    primary: 'green'

  features:
    - search.highlight
    - search.share
    - search.suggest

site_author: Jakob Hærvig
site_description: >-
  Open Terrace Documentation

plugins:
  - search
  - mkdocstrings
    default_handler: python
    handlers:
      python:
      rendering:
        show_source: true
  - watch:
        - openterrace

repo_url: https://github.com/OpenTerrace/openterrace-python
edit_uri: blob/main/docs/

nav:
  - index.md
  - User guide:
      - user-guide/equations.md
      - user-guide/verification.md
      - user-guide/validation.md
  - Installation:
      - installation/windows.md
      - installation/macos.md
      - installation/linux.md
  - Source code:
      - source-code/solvers-reference.md
  - Project proposals:
      - project-proposals/contributing-as-a-student.md
      - project-proposals/optimisation-of-thermal-storage-systems.md