site_name: Open Terrace Documentation

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.tracking
    - navigation.sections
  icon:
    repo: fontawesome/brands/github
  palette:
    primary: 'green'

  features:
    - search.highlight
    - search.share
    - search.suggest

site_author: Jakob Hærvig
site_description: >-
  Open Terrace Documentation

plugins:
    - mkdocstrings:
        handlers:
            python:
                setup_commands:
                  - import sys
                  - sys.path.append("openterrace")

repo_url: https://github.com/OpenTerrace/openterrace-python
edit_uri: blob/main/docs/
repo_name: openterrace-python/

nav:
  - User guide:
      - user-guide/equations.md
      - user-guide/verification.md
      - user-guide/validation.md
  - Installation guide:
      - installation/windows.md
      - installation/macos.md
      - installation/linux.md
  - Source code:
      - source-code/properties-reference.md
      - source-code/solvers-reference.md
  - Project proposals:
      - project-proposals/contributing-as-a-student.md
      - project-proposals/optimisation-of-thermal-storage-systems.md

extra:
  generator: false