site_name: Open Terrace Documentation
site_author: Jakob Hærvig
site_description: >-
  Open Terrace Documentation

repo_url: https://github.com/OpenTerrace/openterrace-python
edit_uri: blob/main/docs/
repo_name: openterrace-python/

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.tracking
    - navigation.sections
  icon:
    repo: fontawesome/brands/github
  features:
    - search.highlight
    - search.share
    - search.suggest
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
  palette:
    scheme: default
    primary: green

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra:
  generator: false

plugins:
    - mkdocstrings:
        handlers:
            python:
                setup_commands:
                  - import sys
                  - sys.path.append("openterrace")
nav:
  - index.md
  - User guide:
      - user-guide/verification.md
      - user-guide/validation.md
  - Installation guide:
      - installation/windows.md
      - installation/macos.md
      - installation/linux.md
  - Source code:
      - source-code/properties-reference.md
      - source-code/particle_models-reference.md
  - Project proposals:
      - project-proposals/index.md
      - project-proposals/AAU/2-sem.md