site_name: Open Terrace Documentation

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.tracking
    - navigation.sections
  icon:
    repo: fontawesome/brands/github
  palette:
    primary: 'green'

  features:
    - search.highlight
    - search.share
    - search.suggest

site_author: Jakob Hærvig
site_description: >-
  Open Terrace Documentation

plugins:
    - mkdocstrings:
        handlers:
            python:
                setup_commands:
                  - import sys
                  - sys.path.append("openterrace")

# plugins:
# - mkdocstrings:
#     default_handler: python
#     handlers:
#       python:
#         rendering:
#           show_source: false
#     custom_templates: templates
#     watch:
#       - src/my_package


repo_url: https://github.com/OpenTerrace/openterrace-python
edit_uri: blob/main/docs/

nav:
  - index.md
  - User guide:
      - user-guide/equations.md
      - user-guide/verification.md
      - user-guide/validation.md
  - Installation:
      - installation/windows.md
      - installation/macos.md
      - installation/linux.md
  - Source code:
      - source-code/properties-reference.md
  - Project proposals:
      - project-proposals/contributing-as-a-student.md
      - project-proposals/optimisation-of-thermal-storage-systems.md