[project]
name = "openterrace"
description = "OpenTerrace is a pure Python framework for thermal energy storage packed bed simulations"
version = "0.0.1"
authors = [
    { name = "Jakob Hærvig" }
    ]
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "numpy",
    "numba==0.55.1",
    "scipy==1.7.3",
    "matplotlib==3.5.1",
    "tqdm==4.64.1",
    "pytest==7.1.3",
]

[project.urls]
"Homepage" = "https://github.com/OpenTerrace/openterrace-python"

[tool.setuptools]
py-modules = []

[build-system]
requires = ["flit_core>=3.2"]
build-backend = "flit_core.buildapi"