[tool.poetry]
name = "openterrace"
description = "OpenTerrace is a pure Python framework for thermal energy storage packed bed simulations"
version = "0.0.1"
authors = [
    "Jakob Hærvig"
    ]
readme = "README.md"
requires-python = ">=3.9"
license = "MIT"

packages = [
    { include = "openterrace"}

]

repository = "https://github.com/OpenTerrace/openterrace-python"
documentation = "https://openterrace.github.io/openterrace-python/"

# Requirements
[tool.poetry.dependencies]
python = "^3.9"

numpy = "^1.19"
numba = "^0.55.1"
scipy = "^1.7.3"
matplotlib = "^3.5.1"
tqdm = "^4.64.1"
pytest = "^7.1.3"

[tool.poetry.group.test.dependencies]
# Cachy frozen to test backwards compatibility for `poetry.utils.cache`.
pytest = "^7.1"

# only used in github actions
[tool.poetry.group.github-actions]
optional = true

[tool.poetry.group.github-actions.dependencies]
pytest-github-actions-annotate-failures = "^0.1.7"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"