name: ci 

on:
  push:
    branches: 
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install mkdocs-material
      - run: pip install mkdocstrings[python]
      - run: pip install markdown-katex
      - run: pip install pytkdocs[numpy-style]
      - run: pip install numpy
      - run: pip install matplotlib
      - run: pip install scipy
      - run: pip install tqdm
      - run: mkdocs gh-deploy --force