name: Generate Docs

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: 'pyproject.toml'

      - name: Install Poetry
        run: pip install poetry

      - name: Install dependencies
        run: poetry install --with doc

      - name: Deploy website
        run: poetry run mkdocs gh-deploy --force