name: Run pytests

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test-pip:
    name: Run tests (with poetry)
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        with:
          python-version-file: 'pyproject.toml'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Fetch all tags
      run: git fetch --prune --unshallow --tags

    - name: Set up Python
      id: python-version
      run: echo "::set-output name=version::$(awk -F'=' '/^python =/ {print $2}' pyproject.toml)"

    - name: Set up Python ${{ steps.python-version.outputs.version }} on ${{ matrix.os }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ steps.python-version.outputs.version }}

    - name: Setup Python environment
      run: |
        python -m pip install --upgrade pip setuptools
        pip install poetry

    - name: Install OpenTerrace and its dependencies
      run: |
        poetry install

    - name: Run tests
      run: |
        poetry run pytest