# This workflow will install the dependencies and run the tests when a push is made to the main branch or when the workflow is manually triggered.

name: Run pytest

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test-pip:
    name: Run test matrix
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["^3.9"]

    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Fetch all tags
      run: git fetch --prune --unshallow --tags

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools
        pip install poetry

    - name: Install OpenTerrace
      run: |
        poetry install

    - name: Run tests
      run: |
        poetry run pytest -n auto