name: Tests

on: [workflow_dispatch]

jobs:
  test-pip:
    name: Run tests (with pip)

    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.x]

    defaults:
      run:
        shell: bash

    steps:
    - uses: actions/checkout@v2

    - run: git fetch --prune --unshallow --tags

    - name: Set up Python ${{ matrix.python-version }} on ${{ matrix.os }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Setup Python environment
      run: |
        python3 -m pip install --upgrade build pip setuptools
        pip3 install numpy numba scipy matplotlib tqdm pytest

    - name: Install OpenTerrace
      run: |
        python3 -m build
        pip3 freeze

    - name: Run tests
      run: |
        python3 -m pytest