name: Merge main back to dev branch

on: [workflow_dispatch]

jobs:
  merge-master-back-to-dev:
    name: Merged main (and tags) back to dev branch
    runs-on: ubuntu-latest

    steps:
    - name: Set Git config
      uses: actions/checkout@v3

    - name: Merge main back to dev
      run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "Github Actions"
          git fetch --unshallow
          git checkout development
          git pull
          git merge --no-ff main -m "Auto-merge main back to dev"
          git push